export const POSTS_ERROR = 'POSTS_ERROR';
export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';

export const MODAL_NULLIFY = 'NULLIFY_MODAL';
export const MODAL_SET_TYPE = 'MODAL_SET_TYPE';
export const MODAL_SET_STATE = 'MODAL_SET_STATE';

export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_WHOAMI = 'AUTH_WHOAMI';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR_NULLIFY = 'AUTH_ERROR_NULLIFY';
