export const POSTS_REQUEST = 'POSTS_REQUEST';
export const POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';

export const MODAL_NULLIFY = 'NULLIFY_MODAL';
export const MODAL_SET_STATE = 'MODAL_SET_STATE';
export const MODAL_SWITCH_TYPE = 'MODAL_SWITCH_TYPE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR_NULLIFY = 'AUTH_ERROR_NULLIFY';
export const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
export const AUTH_REQUEST_WHOAMI = 'AUTH_REQUEST_WHOAMI';
export const AUTH_REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS';
