export const POSTS_REQUEST = 'REQUEST_POSTS';
export const POSTS_REQUEST_ERROR = 'REQUEST_POSTS_ERROR';
export const POSTS_REQUEST_SUCCESS = 'REQUEST_POSTS_SUCCESS';

export const NULLIFY_MODAL = 'NULLIFY_MODAL';
export const SET_MODAL_STATE = 'SET_MODAL_STATE';
export const SET_MODAL_REGISTER = 'SET_MODAL_REGISTER';

export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
